### ISSUE TITLE
When launching the installation of the A11111 fork (vladmandic version), error with missing module named 'rich'

### ISSUE THREAD

**Issue by lstep** [diStyApps/seait#13]
The installation for the vladmandic version of A11111 fails because a dependency is missing ('rich') in the automatically created venv:

```bash
(venv) D:\Stable-Diffusion\seait>seait
installing automatic with at D:\Stable-Diffusion\seait\automatic
Cloning into 'D:\Stable-Diffusion\seait\automatic'...
remote: Enumerating objects: 20808, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 20808 (delta 2), reused 12 (delta 2), pack-reused 20792Receiving objects: 100% (20808/20808), 29.11 MiB | Receiving objects: 100% (20808/20808), 30.74 MiB | 19.38 MiB/s, done.

Resolving deltas: 100% (14647/14647), done.
automatic cloned into D:\Stable-Diffusion\seait\automatic
Creating virtual environment for automatic at D:\Stable-Diffusion\seait\automatic\venv
Virtual environment created for automatic at D:\Stable-Diffusion\seait\automatic\venv
Traceback (most recent call last):
  File "D:\Stable-Diffusion\seait\automatic\launch.py", line 19, in <module>
    setup.parse_args()
  File "D:\Stable-Diffusion\seait\automatic\setup.py", line 446, in parse_args
    from modules.script_loading import preload_extensions
  File "D:\Stable-Diffusion\seait\automatic\modules\script_loading.py", line 3, in <module>
    import modules.errors as errors
  File "D:\Stable-Diffusion\seait\automatic\modules\errors.py", line 3, in <module>
    from rich import print # pylint: disable=redefined-builtin
ModuleNotFoundError: No module named 'rich'

```

**Comment by diStyApps** [comment]
He is making changes it installation broke for now:
https://github.com/vladmandic/automatic/commit/e2f83575da80d3b6d620591809681027cd767c0b

I get different errors, anyway i may need to save commit checkpoint future updates.
I will update about vlad version soon.
