### ISSUE TITLE
text generation webui error on launch

### ISSUE THREAD

**Issue by angrysky56** [diStyApps/seait#16]
text-generation-webui Instructed installation completed
Gradio HTTP request redirected to localhost :)
Traceback (most recent call last):
  File "D:\seait_installers_version_0.1.2\text-generation-webui\server.py", line 44, in <module>
    from modules import chat, shared, training, ui
  File "D:\seait_installers_version_0.1.2\text-generation-webui\modules\training.py", line 13, in <module>
    from peft import (LoraConfig, get_peft_model, prepare_model_for_int8_training,
  File "D:\seait_installers_version_0.1.2\text-generation-webui\venv\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "D:\seait_installers_version_0.1.2\text-generation-webui\venv\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "D:\seait_installers_version_0.1.2\text-generation-webui\venv\lib\site-packages\peft\peft_model.py", line 31, in <module>
    from .tuners import (
  File "D:\seait_installers_version_0.1.2\text-generation-webui\venv\lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "D:\seait_installers_version_0.1.2\text-generation-webui\venv\lib\site-packages\peft\tuners\lora.py", line 40, in <module>
    import bitsandbytes as bnb
  File "D:\seait_installers_version_0.1.2\text-generation-webui\venv\lib\site-packages\bitsandbytes\__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "D:\seait_installers_version_0.1.2\text-generation-webui\venv\lib\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "D:\seait_installers_version_0.1.2\text-generation-webui\venv\lib\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "D:\seait_installers_version_0.1.2\text-generation-webui\venv\lib\site-packages\bitsandbytes\functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "D:\seait_installers_version_0.1.2\text-generation-webui\venv\lib\site-packages\bitsandbytes\cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "D:\seait_installers_version_0.1.2\text-generation-webui\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 97, in run_cuda_setup
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "D:\seait_installers_version_0.1.2\text-generation-webui\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 403, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "D:\seait_installers_version_0.1.2\text-generation-webui\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 264, in determine_cuda_runtime_lib_path
    lib_ld_cuda_libs = find_cuda_lib_in(candidate_env_vars["PATH"])
  File "D:\seait_installers_version_0.1.2\text-generation-webui\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 202, in find_cuda_lib_in
    return get_cuda_runtime_lib_paths(
  File "D:\seait_installers_version_0.1.2\text-generation-webui\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 186, in get_cuda_runtime_lib_paths
    return {
  File "D:\seait_installers_version_0.1.2\text-generation-webui\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 189, in <setcomp>
    if (path / CUDA_RUNTIME_LIB).is_file()
  File "C:\Users\angry\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1322, in is_file
    return S_ISREG(self.stat().st_mode)
  File "C:\Users\angry\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
OSError: [WinError 1920] The file cannot be accessed by the system: 'C:\\Users\\angry\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe\\cudart64_110.dll'

**Comment by angrysky56** [comment]
Do I need to do this?
https://stackoverflow.com/questions/65569706/getting-os-error-python-library-not-found/65569809#65569809

**Comment by diStyApps** [comment]
Did you installed CUDA Toolkit ?
https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exe_local

**Comment by angrysky56** [comment]
I have version 12.1 for 11 (not 10 if that matters?) in my cuda path, sorry I don't know much about coding or computers.

 I am absolutely loving comfyUI, which I may have never tried if not for you so thank you very much btw. I have a ton of models/loras in my D drive folders that I just call from the webuiuser.bat in automatic1111 with ckpt-dir "D:\modeloverflow" etc, it would be cool to keep a list that could be added as a general pointer for installed apps if possible.

**Comment by diStyApps** [comment]
Thank very much that's makes me happy, i have added symlink feature you can try it.
Reopen issue or open new one if problem not solved.
