### ISSUE TITLE
bark no audio backend

### ISSUE THREAD

**Issue by seruko11** [diStyApps/seait#23]
trying to create a cloned voice but I get this error, may be related to either soundfile or PySoundFile, or mor likely missing torch audio installation/env

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\venv\Lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\venv\Lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\venv\Lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\venv\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\venv\Lib\site-packages\gradio\helpers.py", line 588, in tracked_fn
    response = fn(*args)
               ^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\bark\clonevoice.py", line 20, in clone_voice
    wav, sr = torchaudio.load(audio_filepath)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\venv\Lib\site-packages\torchaudio\backend\no_backend.py", line 16, in load
    raise RuntimeError("No audio I/O backend is available.")
RuntimeError: No audio I/O backend is available.

**Comment by diStyApps** [comment]
I also got that, they didn't stated in the repo at time i added bark  it will be added next update.
Meanwhile you can 

`
pip install soundfile
`

**Comment by seruko11** [comment]
@diStyApps does this need to be run in the bark-gui dir?
sorry for the dumb question

**Comment by diStyApps** [comment]
It's not a dumb question, it's a good question.
But sorry for confusing you,
i have uploaded a fix  [seait.v0.1.4_bark_soundfile_fix.zip ](https://github.com/diStyApps/seait/releases/download/0.1.4/seait.v0.1.4.zip)

For most projects i check it they installed and work properly.
But with bark, found myself playing with it for hours, so i was aware of that.

You don't have to do this you can download the fix, but now if something like that happens you will know how to activate environment.

To activate any environment in any project, be in the root folder.

For example: `C:\DEMO\seait\bark-gui`

Type `CMD `in the Navigation bar.

Then type: `venv\Scripts\activate`

For example: `C:\DEMO\seait\bark-gui>venv\Scripts\activate`

After the environment is activated, it should look like this:

`(venv) C:\DEMO\seait\bgui>venv\Scripts\activate`

And then type `pip install soundfile`

**Comment by seruko11** [comment]
@diStyApps Thank you very much!

**Comment by seruko11** [comment]
@diStyApps Okay, I can now make prompts but they crash rather than render an output, should I create a new issue and close this one or keep posting here? What's your prefence

**Comment by diStyApps** [comment]
Close this one and open new one.
