### ISSUE TITLE
Bark-GUI - can't generate audio with custom voice

### ISSUE THREAD

**Issue by seruko11** [diStyApps/seait#25]
I used Bark-GUI to clone a prompt from an audio sample, that worked great. When I try to create speech from text using the custom voice I get the following error, I am able to create arbitrary audio from text using the pre-built prompts. This error only happens when I have "use coarse history" checked. Possibly this is a  bark-gui problem.

Generating Text (1/1) -> custom\MeMyselfAndI:`Hello Sir, How can I help you today?`
Traceback (most recent call last):
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\venv\Lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\venv\Lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\venv\Lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\venv\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\venv\Lib\site-packages\gradio\helpers.py", line 588, in tracked_fn
    response = fn(*args)
               ^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\webui.py", line 114, in generate_text_to_speech
    audio_array = generate_audio(text, selected_speaker, text_temp, waveform_temp)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\bark\api.py", line 113, in generate_audio
    out = semantic_to_waveform(
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\bark\api.py", line 54, in semantic_to_waveform
    coarse_tokens = generate_coarse(
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\toor\Desktop\Ai\seait_installers_version_0.1.4\bark-gui\bark\generation.py", line 592, in generate_coarse
    round(x_coarse_history.shape[-1] / len(x_semantic_history), 1)
AssertionError

**Comment by seruko11** [comment]
Someone else has opened exactly the same ticket in bark-gui. I'm going to call this a bark-gui problem and close this issue. Thanks again for your platform, it's amazing.
