### ISSUE TITLE
[Bug]: Error while installing Text Generation web UI

### ISSUE THREAD

**Issue by Vetrov0x** [diStyApps/seait#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Bug Description

Traceback (most recent call last):
  File "C:\Users\Daedar\seait\text-generation-webui\download-model.py", line 20, in <module>
    import tqdm
ModuleNotFoundError: No module named 'tqdm'
text-generation-webui Instructed installation completed
Traceback (most recent call last):
  File "C:\Users\Daedar\seait\text-generation-webui\server.py", line 12, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

### Step-by-step instructions to reproduce the issue.

Just installing  Text Generation web UI from the GUI

### Expected Behavior

Launch after installation

### Current Behavior

Error at:

Traceback (most recent call last):
  File "C:\Users\Daedar\seait\text-generation-webui\download-model.py", line 20, in <module>
    import tqdm
ModuleNotFoundError: No module named 'tqdm'
text-generation-webui Instructed installation completed
Traceback (most recent call last):
  File "C:\Users\Daedar\seait\text-generation-webui\server.py", line 12, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

### Version or Commit where the problem happens

0.1.4.7 

### Console logs

```Shell
installing text-generation-webui with at C:\Users\Daedar\seait\text-generation-webui
Cloning into 'C:\Users\Daedar\seait\text-generation-webui'...
remote: Enumerating objects: 10951, done.
remote: Counting objects: 100% (2794/2794), done.
remote: Compressing objects: 100% (478/478), done.
remote: Total 10951 (delta 2502), reused 2458 (delta 2313), pack-reused 8157
0% (10951/10951)
Receiving objects: 100% (10951/10951), 3.51 MiB | 9.33 MiB/s, done.
Resolving deltas: 100% (7475/7475), done.
text-generation-webui cloned into C:\Users\Daedar\seait\text-generation-webui
Creating virtual environment for text-generation-webui at C:\Users\Daedar\seait\text-generation-webui\venv
Virtual environment created for text-generation-webui at C:\Users\Daedar\seait\text-generation-webui\venv
Installing requirements for text-generation-webui at C:\Users\Daedar\seait\text-generation-webui\venv
Ignoring bitsandbytes: markers 'platform_system != "Windows"' don't match your environment
Collecting bitsandbytes==0.41.1 (from -r requirements.txt (line 27))
  Downloading https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl (152.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.7/152.7 MB 8.4 MB/s eta 0:00:00
ERROR: auto_gptq-0.4.2+cu117-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.
text-generation-webui requirements installed at C:\Users\Daedar\seait\text-generation-webui\venv
Executing install instructions for text-generation-webui
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117
Collecting torch
  Using cached https://download.pytorch.org/whl/cu117/torch-2.0.1%2Bcu117-cp311-cp311-win_amd64.whl (2343.6 MB)
Collecting torchvision
  Using cached https://download.pytorch.org/whl/cu117/torchvision-0.15.2%2Bcu117-cp311-cp311-win_amd64.whl (4.9 MB)
Collecting torchaudio
  Using cached https://download.pytorch.org/whl/cu117/torchaudio-2.0.2%2Bcu117-cp311-cp311-win_amd64.whl (2.5 MB)
Collecting filelock (from torch)
  Obtaining dependency information for filelock from https://files.pythonhosted.org/packages/52/90/45223db4e1df30ff14e8aebf9a1bf0222da2e7b49e53692c968f36817812/filelock-3.12.3-py3-none-any.whl.metadata
  Using cached filelock-3.12.3-py3-none-any.whl.metadata (2.7 kB)
Collecting typing-extensions (from torch)
  Obtaining dependency information for typing-extensions from https://files.pythonhosted.org/packages/ec/6b/63cc3df74987c36fe26157ee12e09e8f9db4de771e0f3404263117e75b95/typing_extensions-4.7.1-py3-none-any.whl.metadata
  Using cached typing_extensions-4.7.1-py3-none-any.whl.metadata (3.1 kB)
Collecting sympy (from torch)
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting networkx (from torch)
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting jinja2 (from torch)
  Using cached https://download.pytorch.org/whl/Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting numpy (from torchvision)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/72/b2/02770e60c4e2f7e158d923ab0dea4e9f146a2dbf267fec6d8dc61d475689/numpy-1.25.2-cp311-cp311-win_amd64.whl.metadata
  Using cached numpy-1.25.2-cp311-cp311-win_amd64.whl.metadata (5.7 kB)
Collecting requests (from torchvision)
  Obtaining dependency information for requests from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)
  Obtaining dependency information for pillow!=8.3.*,>=5.3.0 from https://files.pythonhosted.org/packages/66/d4/054e491f0880bf0119ee79cdc03264e01d5732e06c454da8c69b83a7c8f2/Pillow-10.0.0-cp311-cp311-win_amd64.whl.metadata
  Using cached Pillow-10.0.0-cp311-cp311-win_amd64.whl.metadata (9.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Obtaining dependency information for MarkupSafe>=2.0 from https://files.pythonhosted.org/packages/be/bb/08b85bc194034efbf572e70c3951549c8eca0ada25363afc154386b5390a/MarkupSafe-2.1.3-cp311-cp311-win_amd64.whl.metadata
  Using cached MarkupSafe-2.1.3-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Collecting charset-normalizer<4,>=2 (from requests->torchvision)
  Obtaining dependency information for charset-normalizer<4,>=2 from https://files.pythonhosted.org/packages/91/6e/db0e545302bf93b6dbbdc496dd192c7f8e8c3bb1584acba069256d8b51d4/charset_normalizer-3.2.0-cp311-cp311-win_amd64.whl.metadata
  Using cached charset_normalizer-3.2.0-cp311-cp311-win_amd64.whl.metadata (31 kB)
Collecting idna<4,>=2.5 (from requests->torchvision)
  Using cached https://download.pytorch.org/whl/idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1 (from requests->torchvision)
  Obtaining dependency information for urllib3<3,>=1.21.1 from https://files.pythonhosted.org/packages/9b/81/62fd61001fa4b9d0df6e31d47ff49cfa9de4af03adecf339c7bc30656b37/urllib3-2.0.4-py3-none-any.whl.metadata
  Using cached urllib3-2.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting certifi>=2017.4.17 (from requests->torchvision)
  Obtaining dependency information for certifi>=2017.4.17 from https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl.metadata
  Using cached certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Collecting mpmath>=0.19 (from sympy->torch)
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached Pillow-10.0.0-cp311-cp311-win_amd64.whl (2.5 MB)
Using cached filelock-3.12.3-py3-none-any.whl (11 kB)
Using cached numpy-1.25.2-cp311-cp311-win_amd64.whl (15.5 MB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Using cached charset_normalizer-3.2.0-cp311-cp311-win_amd64.whl (96 kB)
Using cached MarkupSafe-2.1.3-cp311-cp311-win_amd64.whl (17 kB)
Using cached urllib3-2.0.4-py3-none-any.whl (123 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision, torchaudio
Successfully installed MarkupSafe-2.1.3 certifi-2023.7.22 charset-normalizer-3.2.0 filelock-3.12.3 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 numpy-1.25.2 pillow-10.0.0 requests-2.31.0 sympy-1.12 torch-2.0.1+cu117 torchaudio-2.0.2+cu117 torchvision-0.15.2+cu117 typing-extensions-4.7.1 urllib3-2.0.4
text-generation-webui Instructed installation completed
Collecting bitsandbytes==0.37.2
  Using cached https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.37.2-py3-none-any.whl (66.7 MB)
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.37.2
text-generation-webui Instructed installation completed
Traceback (most recent call last):
  File "C:\Users\Daedar\seait\text-generation-webui\download-model.py", line 20, in <module>
    import tqdm
ModuleNotFoundError: No module named 'tqdm'
text-generation-webui Instructed installation completed
Traceback (most recent call last):
  File "C:\Users\Daedar\seait\text-generation-webui\server.py", line 12, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
```

**Comment by AsaTyr2018** [comment]
Hey there.
looks like a few modules aren´t installed correctly. 
try "Delete Venc" and then Update to recreate the venv. 

Mostly that worked for me.

**Comment by AsaTyr2018** [comment]
@Vetrov0x did you try to renew the VENV dir?

**Comment by Vetrov0x** [comment]
Tried, didn't work. While update I got this error:

ERROR: auto_gptq-0.4.2+cu117-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

**Comment by AsaTyr2018** [comment]
> Tried, didn't work. While update I got this error:
> 
> ERROR: auto_gptq-0.4.2+cu117-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

thats strange. as far as i see you are on windows. so that lib has to be working. 
Uninstall the whole textgui. stop seait and start it again. 

and please give me a pip list (cmd -> pip list)

**Comment by AsaTyr2018** [comment]
> Tried, didn't work. While update I got this error:
> 
> ERROR: auto_gptq-0.4.2+cu117-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

Is the Issue still Active or has it been solved?

**Comment by royaltongue** [comment]
I'm having a similar error when trying to install Bark-GUI. When installing:
`ERROR: fairseq-0.12.4-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.`

And when running:
```
Traceback (most recent call last):
  File "C:\Users\localuser\seait\bark-gui\webui.py", line 5, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
```

And from `pip list`:
```
Package                   Version
------------------------- ------------
aiofiles                  23.2.1
altair                    5.1.1
annotated-types           0.5.0
anyio                     3.7.1
attrs                     23.1.0
boto3                     1.28.53
botocore                  1.31.53
certifi                   2023.7.22
charset-normalizer        3.2.0
click                     8.1.7
colorama                  0.4.6
contourpy                 1.1.1
cycler                    0.11.0
einops                    0.6.1
encodec                   0.1.1
fastapi                   0.103.1
ffmpy                     0.3.1
filelock                  3.12.4
fonttools                 4.42.1
fsspec                    2023.9.2
funcy                     2.0
gradio                    3.44.4
gradio_client             0.5.1
h11                       0.14.0
httpcore                  0.18.0
httpx                     0.25.0
huggingface-hub           0.16.4
idna                      3.4
importlib-resources       6.1.0
intelhex                  2.3.0
Jinja2                    3.1.2
jmespath                  1.0.1
jsonschema                4.19.1
jsonschema-specifications 2023.7.1
kiwisolver                1.4.5
MarkupSafe                2.1.3
matplotlib                3.8.0
mpmath                    1.3.0
networkx                  3.1
numpy                     1.26.0
orjson                    3.9.7
packaging                 23.1
pandas                    2.1.1
Pillow                    10.0.1
pydantic                  2.3.0
pydantic_core             2.6.3
pydub                     0.25.1
pyparsing                 3.1.1
pyserial                  3.5
python-dateutil           2.8.2
python-multipart          0.0.6
pytz                      2023.3.post1
PyYAML                    6.0.1
referencing               0.30.2
regex                     2023.8.8
requests                  2.31.0
rpds-py                   0.10.3
s3transfer                0.6.2
safetensors               0.3.3
scipy                     1.11.2
semantic-version          2.10.0
six                       1.16.0
sniffio                   1.3.0
starlette                 0.27.0
suno-bark                 0.0.1a0
sympy                     1.12
tokenizers                0.13.3
toolz                     0.12.0
torch                     2.0.1
torchaudio                2.0.2
tqdm                      4.66.1
transformers              4.33.2
typing_extensions         4.8.0
tzdata                    2023.3
urllib3                   1.26.16
uvicorn                   0.23.2
websockets                11.0.3
```

**Comment by AsaTyr2018** [comment]
@royaltongue 
Hmm, I often come across this kind of issue. It seems like you have Gradio installed in your local pip, but the environment doesn't recognize it.

Please check this folder to see if you can find Gradio there:
TextGen\venv\Lib\site-packages

In my case, it's located in the 'TextGen' folder. However, the 'venv' folder is present in every Python environment in use.

**Comment by royaltongue** [comment]
It doesn't seem like gradio is in the `site-packages` folder. Is there a way I can add it?

**Comment by AsaTyr2018** [comment]
@royaltongue 
remove the venv via the gui and update it. it should drag all required files along.

**Comment by Dhiman-Ajay** [comment]
https://github.com/C0untFloyd/bark-gui/issues/87#issuecomment-1793725560

This worked in my case, try it and let us know
