### ISSUE TITLE
[Bug]: AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by vararth** [diStyApps/seait#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Bug Description

Unable to run and install Kandinsky

### Step-by-step instructions to reproduce the issue.

Simple Install button, unable to launch

### Expected Behavior

Should install everything and launch correctly

### Current Behavior

Not launching and giving the error as mentioned

### Version or Commit where the problem happens

0.1.4.8

### What platforms do you use SEAIT ?

Windows

### What Python version are you running on ?

3.11.8

### What GPU are you running SEAIT on?

RTX 3050

### How much GPU VRAM are you running SEAIT on?

N.A.

### On what Project the issue are you facing?

Kandinsky

### Console logs

```Shell
launching Kandinsky-2 at C:\Users\Admin\seait\Kandinsky-2
C:\Users\Admin\seait\Kandinsky-2\venv\Lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\Admin\seait\Kandinsky-2\venv\Lib\site-packages\huggingface_hub\file_download.py:678: FutureWarning: 'cached_download' is the legacy way to download files from the HF hub, please consider upgrading to 'hf_hub_download'
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\Admin\seait\Kandinsky-2\app.py", line 13, in <module>
    model = get_kandinsky2(
            ^^^^^^^^^^^^^^^
  File "C:\Users\Admin\seait\Kandinsky-2\venv\Lib\site-packages\kandinsky2\__init__.py", line 180, in get_kandinsky2
    model = get_kandinsky2_1(
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\seait\Kandinsky-2\venv\Lib\site-packages\kandinsky2\__init__.py", line 160, in get_kandinsky2_1
    model = Kandinsky2_1(config, cache_model_name, cache_prior_name, device, task_type=task_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\seait\Kandinsky-2\venv\Lib\site-packages\kandinsky2\kandinsky2_1_model.py", line 64, in __init__
    self.clip_model, self.preprocess = clip.load(
                                       ^^^^^^^^^^
  File "C:\Users\Admin\seait\Kandinsky-2\venv\Lib\site-packages\clip\clip.py", line 139, in load
    model = build_model(state_dict or model.state_dict()).to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\seait\Kandinsky-2\venv\Lib\site-packages\torch\nn\modules\module.py", line 1152, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\seait\Kandinsky-2\venv\Lib\site-packages\torch\nn\modules\module.py", line 802, in _apply
    module._apply(fn)
  File "C:\Users\Admin\seait\Kandinsky-2\venv\Lib\site-packages\torch\nn\modules\module.py", line 802, in _apply
    module._apply(fn)
  File "C:\Users\Admin\seait\Kandinsky-2\venv\Lib\site-packages\torch\nn\modules\module.py", line 825, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\Users\Admin\seait\Kandinsky-2\venv\Lib\site-packages\torch\nn\modules\module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\seait\Kandinsky-2\venv\Lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

### Additional information

Looking for support - and hopefully an extension to inference with Kandinsky 2.2 :)

**Comment by ssjrocks** [comment]
asus 5080 core 9 285k 128gb ram... i came here from google... but ive probably got a very dirty python situation.... i play with alot of ai software and barely know what im doing lol
```

installing ComfyUI with at C:\Users\ssjro\seait\ComfyUI

Cloning into 'C:\Users\ssjro\seait\ComfyUI'...
remote: Enumerating objects: 20079, done.
remote: Counting objects: 100% (186/186), done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 20079 (delta 148), reused 73 (delta 73), pack-reused 19893 (from 3)
Receiving objects: 100% (20079/20079), 68.98 MiB | 3.11 MiB/s, done.
Resolving deltas: 100% (13331/13331), done.
ComfyUI cloned into C:\Users\ssjro\seait\ComfyUI
Creating virtual environment for ComfyUI at C:\Users\ssjro\seait\ComfyUI\venv
Virtual environment created for ComfyUI at C:\Users\ssjro\seait\ComfyUI\venv
Installing requirements for ComfyUI at C:\Users\ssjro\seait\ComfyUI\venv
Collecting comfyui-frontend-package==1.21.7 (from -r requirements.txt (line 1))
  Downloading comfyui_frontend_package-1.21.7-py3-none-any.whl.metadata (117 bytes)
Collecting comfyui-workflow-templates==0.1.25 (from -r requirements.txt (line 2))
  Downloading comfyui_workflow_templates-0.1.25-py3-none-any.whl.metadata (55 kB)
Collecting comfyui-embedded-docs==0.2.0 (from -r requirements.txt (line 3))
  Downloading comfyui_embedded_docs-0.2.0-py3-none-any.whl.metadata (1.3 kB)
Collecting torch (from -r requirements.txt (line 4))
  Downloading torch-2.7.1-cp313-cp313-win_amd64.whl.metadata (28 kB)
Collecting torchsde (from -r requirements.txt (line 5))
  Using cached torchsde-0.2.6-py3-none-any.whl.metadata (5.3 kB)
Collecting torchvision (from -r requirements.txt (line 6))
  Downloading torchvision-0.22.1-cp313-cp313-win_amd64.whl.metadata (6.1 kB)
Collecting torchaudio (from -r requirements.txt (line 7))
  Downloading torchaudio-2.7.1-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Collecting numpy>=1.25.0 (from -r requirements.txt (line 8))
  Downloading numpy-2.2.6-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting einops (from -r requirements.txt (line 9))
  Using cached einops-0.8.1-py3-none-any.whl.metadata (13 kB)
Collecting transformers>=4.28.1 (from -r requirements.txt (line 10))
  Downloading transformers-4.52.4-py3-none-any.whl.metadata (38 kB)
Collecting tokenizers>=0.13.3 (from -r requirements.txt (line 11))
  Downloading tokenizers-0.21.1-cp39-abi3-win_amd64.whl.metadata (6.9 kB)
Collecting sentencepiece (from -r requirements.txt (line 12))
  Using cached sentencepiece-0.2.0.tar.gz (2.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting safetensors>=0.4.2 (from -r requirements.txt (line 13))
  Using cached safetensors-0.5.3-cp38-abi3-win_amd64.whl.metadata (3.9 kB)
Collecting aiohttp>=3.11.8 (from -r requirements.txt (line 14))
  Downloading aiohttp-3.12.9-cp313-cp313-win_amd64.whl.metadata (7.9 kB)
Collecting yarl>=1.18.0 (from -r requirements.txt (line 15))
  Downloading yarl-1.20.0-cp313-cp313-win_amd64.whl.metadata (74 kB)
Collecting pyyaml (from -r requirements.txt (line 16))
  Downloading PyYAML-6.0.2-cp313-cp313-win_amd64.whl.metadata (2.1 kB)
Collecting Pillow (from -r requirements.txt (line 17))
  Downloading pillow-11.2.1-cp313-cp313-win_amd64.whl.metadata (9.1 kB)
Collecting scipy (from -r requirements.txt (line 18))
  Downloading scipy-1.15.3-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting tqdm (from -r requirements.txt (line 19))
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting psutil (from -r requirements.txt (line 20))
  Using cached psutil-7.0.0-cp37-abi3-win_amd64.whl.metadata (23 kB)
Collecting kornia>=0.7.1 (from -r requirements.txt (line 23))
  Downloading kornia-0.8.1-py2.py3-none-any.whl.metadata (17 kB)
Collecting spandrel (from -r requirements.txt (line 24))
  Downloading spandrel-0.4.1-py3-none-any.whl.metadata (15 kB)
Collecting soundfile (from -r requirements.txt (line 25))
  Using cached soundfile-0.13.1-py2.py3-none-win_amd64.whl.metadata (16 kB)
Collecting av>=14.2.0 (from -r requirements.txt (line 26))
  Downloading av-14.4.0-cp313-cp313-win_amd64.whl.metadata (4.7 kB)
Collecting pydantic~=2.0 (from -r requirements.txt (line 27))
  Downloading pydantic-2.11.5-py3-none-any.whl.metadata (67 kB)
Collecting filelock (from torch->-r requirements.txt (line 4))
  Using cached filelock-3.18.0-py3-none-any.whl.metadata (2.9 kB)
Collecting typing-extensions>=4.10.0 (from torch->-r requirements.txt (line 4))
  Downloading typing_extensions-4.14.0-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy>=1.13.3 (from torch->-r requirements.txt (line 4))
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch->-r requirements.txt (line 4))
  Downloading networkx-3.5-py3-none-any.whl.metadata (6.3 kB)
Collecting jinja2 (from torch->-r requirements.txt (line 4))
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec (from torch->-r requirements.txt (line 4))
  Downloading fsspec-2025.5.1-py3-none-any.whl.metadata (11 kB)
Collecting setuptools (from torch->-r requirements.txt (line 4))
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting trampoline>=0.1.2 (from torchsde->-r requirements.txt (line 5))
  Using cached trampoline-0.1.2-py3-none-any.whl.metadata (10 kB)
Collecting huggingface-hub<1.0,>=0.30.0 (from transformers>=4.28.1->-r requirements.txt (line 10))
  Downloading huggingface_hub-0.32.4-py3-none-any.whl.metadata (14 kB)
Collecting packaging>=20.0 (from transformers>=4.28.1->-r requirements.txt (line 10))
  Using cached packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Collecting regex!=2019.12.17 (from transformers>=4.28.1->-r requirements.txt (line 10))
  Downloading regex-2024.11.6-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting requests (from transformers>=4.28.1->-r requirements.txt (line 10))
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp>=3.11.8->-r requirements.txt (line 14))
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.1.2 (from aiohttp>=3.11.8->-r requirements.txt (line 14))
  Using cached aiosignal-1.3.2-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting attrs>=17.3.0 (from aiohttp>=3.11.8->-r requirements.txt (line 14))
  Using cached attrs-25.3.0-py3-none-any.whl.metadata (10 kB)
Collecting frozenlist>=1.1.1 (from aiohttp>=3.11.8->-r requirements.txt (line 14))
  Downloading frozenlist-1.6.2-cp313-cp313-win_amd64.whl.metadata (17 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp>=3.11.8->-r requirements.txt (line 14))
  Downloading multidict-6.4.4-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp>=3.11.8->-r requirements.txt (line 14))
  Downloading propcache-0.3.1-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting idna>=2.0 (from yarl>=1.18.0->-r requirements.txt (line 15))
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting colorama (from tqdm->-r requirements.txt (line 19))
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting kornia_rs>=0.1.9 (from kornia>=0.7.1->-r requirements.txt (line 23))
  Downloading kornia_rs-0.1.9-cp313-cp313-win_amd64.whl.metadata (12 kB)
Collecting cffi>=1.0 (from soundfile->-r requirements.txt (line 25))
  Downloading cffi-1.17.1-cp313-cp313-win_amd64.whl.metadata (1.6 kB)
Collecting annotated-types>=0.6.0 (from pydantic~=2.0->-r requirements.txt (line 27))
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.33.2 (from pydantic~=2.0->-r requirements.txt (line 27))
  Downloading pydantic_core-2.33.2-cp313-cp313-win_amd64.whl.metadata (6.9 kB)
Collecting typing-inspection>=0.4.0 (from pydantic~=2.0->-r requirements.txt (line 27))
  Downloading typing_inspection-0.4.1-py3-none-any.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=1.0->soundfile->-r requirements.txt (line 25))
  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch->-r requirements.txt (line 4))
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch->-r requirements.txt (line 4))
  Downloading MarkupSafe-3.0.2-cp313-cp313-win_amd64.whl.metadata (4.1 kB)
Collecting charset-normalizer<4,>=2 (from requests->transformers>=4.28.1->-r requirements.txt (line 10))
  Downloading charset_normalizer-3.4.2-cp313-cp313-win_amd64.whl.metadata (36 kB)
Collecting urllib3<3,>=1.21.1 (from requests->transformers>=4.28.1->-r requirements.txt (line 10))
  Downloading urllib3-2.4.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->transformers>=4.28.1->-r requirements.txt (line 10))
  Downloading certifi-2025.4.26-py3-none-any.whl.metadata (2.5 kB)
Downloading comfyui_frontend_package-1.21.7-py3-none-any.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 8.9 MB/s eta 0:00:00
Downloading comfyui_workflow_templates-0.1.25-py3-none-any.whl (66.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.2/66.2 MB 6.6 MB/s eta 0:00:00
Downloading comfyui_embedded_docs-0.2.0-py3-none-any.whl (690 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 690.2/690.2 kB 7.5 MB/s eta 0:00:00
Downloading torch-2.7.1-cp313-cp313-win_amd64.whl (216.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.1/216.1 MB 4.4 MB/s eta 0:00:00
Using cached torchsde-0.2.6-py3-none-any.whl (61 kB)
Downloading torchvision-0.22.1-cp313-cp313-win_amd64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 5.0 MB/s eta 0:00:00
Downloading torchaudio-2.7.1-cp313-cp313-win_amd64.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 1.7 MB/s eta 0:00:00
Downloading numpy-2.2.6-cp313-cp313-win_amd64.whl (12.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.6/12.6 MB 6.6 MB/s eta 0:00:00
Using cached einops-0.8.1-py3-none-any.whl (64 kB)
Downloading transformers-4.52.4-py3-none-any.whl (10.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 3.4 MB/s eta 0:00:00
Downloading tokenizers-0.21.1-cp39-abi3-win_amd64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 5.3 MB/s eta 0:00:00
Using cached safetensors-0.5.3-cp38-abi3-win_amd64.whl (308 kB)
Downloading aiohttp-3.12.9-cp313-cp313-win_amd64.whl (445 kB)
Downloading yarl-1.20.0-cp313-cp313-win_amd64.whl (92 kB)
Downloading PyYAML-6.0.2-cp313-cp313-win_amd64.whl (156 kB)
Downloading pillow-11.2.1-cp313-cp313-win_amd64.whl (2.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 7.7 MB/s eta 0:00:00
Downloading scipy-1.15.3-cp313-cp313-win_amd64.whl (41.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.0/41.0 MB 4.1 MB/s eta 0:00:00
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Using cached psutil-7.0.0-cp37-abi3-win_amd64.whl (244 kB)
Downloading kornia-0.8.1-py2.py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 8.6 MB/s eta 0:00:00
Downloading spandrel-0.4.1-py3-none-any.whl (305 kB)
Using cached soundfile-0.13.1-py2.py3-none-win_amd64.whl (1.0 MB)
Downloading av-14.4.0-cp313-cp313-win_amd64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 2.4 MB/s eta 0:00:00
Downloading pydantic-2.11.5-py3-none-any.whl (444 kB)
Downloading pydantic_core-2.33.2-cp313-cp313-win_amd64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 7.1 MB/s eta 0:00:00
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Using cached aiosignal-1.3.2-py2.py3-none-any.whl (7.6 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached attrs-25.3.0-py3-none-any.whl (63 kB)
Downloading cffi-1.17.1-cp313-cp313-win_amd64.whl (182 kB)
Downloading frozenlist-1.6.2-cp313-cp313-win_amd64.whl (46 kB)
Downloading huggingface_hub-0.32.4-py3-none-any.whl (512 kB)
Downloading fsspec-2025.5.1-py3-none-any.whl (199 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Downloading kornia_rs-0.1.9-cp313-cp313-win_amd64.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 4.3 MB/s eta 0:00:00
Downloading multidict-6.4.4-cp313-cp313-win_amd64.whl (38 kB)
Using cached packaging-25.0-py3-none-any.whl (66 kB)
Downloading propcache-0.3.1-cp313-cp313-win_amd64.whl (44 kB)
Downloading regex-2024.11.6-cp313-cp313-win_amd64.whl (273 kB)
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 5.4 MB/s eta 0:00:00
Using cached trampoline-0.1.2-py3-none-any.whl (5.2 kB)
Downloading typing_extensions-4.14.0-py3-none-any.whl (43 kB)
Downloading typing_inspection-0.4.1-py3-none-any.whl (14 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached filelock-3.18.0-py3-none-any.whl (16 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading networkx-3.5-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 8.4 MB/s eta 0:00:00
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached setuptools-80.9.0-py3-none-any.whl (1.2 MB)
Downloading certifi-2025.4.26-py3-none-any.whl (159 kB)
Downloading charset_normalizer-3.4.2-cp313-cp313-win_amd64.whl (105 kB)
Downloading MarkupSafe-3.0.2-cp313-cp313-win_amd64.whl (15 kB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Downloading urllib3-2.4.0-py3-none-any.whl (128 kB)
Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Building wheels for collected packages: sentencepiece
  Building wheel for sentencepiece (pyproject.toml) ... done
  Created wheel for sentencepiece: filename=sentencepiece-0.2.0-cp313-cp313-win_amd64.whl size=995248 sha256=c167a750e22cd72e313257298557327dc0ea9e1a217ba64bdae55038370cb186
  Stored in directory: c:\users\ssjro\appdata\local\pip\cache\wheels\02\3d\f0\8dbb11925fbd58340b128ae9334ae7028332d7a5751738f616
Successfully built sentencepiece
Installing collected packages: trampoline, sentencepiece, mpmath, urllib3, typing-extensions, sympy, setuptools, safetensors, regex, pyyaml, pycparser, psutil, propcache, Pillow, packaging, numpy, networkx, multidict, MarkupSafe, kornia_rs, idna, fsspec, frozenlist, filelock, einops, comfyui-workflow-templates, comfyui-frontend-package, comfyui-embedded-docs, colorama, charset-normalizer, certifi, av, attrs, annotated-types, aiohappyeyeballs, yarl, typing-inspection, tqdm, scipy, requests, pydantic-core, jinja2, cffi, aiosignal, torch, soundfile, pydantic, huggingface-hub, aiohttp, torchvision, torchsde, torchaudio, tokenizers, kornia, transformers, spandrel
Successfully installed MarkupSafe-3.0.2 Pillow-11.2.1 aiohappyeyeballs-2.6.1 aiohttp-3.12.9 aiosignal-1.3.2 annotated-types-0.7.0 attrs-25.3.0 av-14.4.0 certifi-2025.4.26 cffi-1.17.1 charset-normalizer-3.4.2 colorama-0.4.6 comfyui-embedded-docs-0.2.0 comfyui-frontend-package-1.21.7 comfyui-workflow-templates-0.1.25 einops-0.8.1 filelock-3.18.0 frozenlist-1.6.2 fsspec-2025.5.1 huggingface-hub-0.32.4 idna-3.10 jinja2-3.1.6 kornia-0.8.1 kornia_rs-0.1.9 mpmath-1.3.0 multidict-6.4.4 networkx-3.5 numpy-2.2.6 packaging-25.0 propcache-0.3.1 psutil-7.0.0 pycparser-2.22 pydantic-2.11.5 pydantic-core-2.33.2 pyyaml-6.0.2 regex-2024.11.6 requests-2.32.3 safetensors-0.5.3 scipy-1.15.3 sentencepiece-0.2.0 setuptools-80.9.0 soundfile-0.13.1 spandrel-0.4.1 sympy-1.14.0 tokenizers-0.21.1 torch-2.7.1 torchaudio-2.7.1 torchsde-0.2.6 torchvision-0.22.1 tqdm-4.67.1 trampoline-0.1.2 transformers-4.52.4 typing-extensions-4.14.0 typing-inspection-0.4.1 urllib3-2.4.0 yarl-1.20.0

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: C:\Users\ssjro\seait\ComfyUI\venv\Scripts\python.exe -m pip install --upgrade pip
ComfyUI requirements installed at C:\Users\ssjro\seait\ComfyUI\venv
Executing install instructions for ComfyUI
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117
ERROR: Could not find a version that satisfies the requirement torch==1.13.1 (from versions: 2.6.0, 2.7.0, 2.7.1)

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: C:\Users\ssjro\seait\ComfyUI\venv\Scripts\python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for torch==1.13.1
ComfyUI Instructed installation completed
Checkpoint files will always be loaded safely.
Traceback (most recent call last):
  File "C:\Users\ssjro\seait\ComfyUI\main.py", line 130, in <module>
    import execution
  File "C:\Users\ssjro\seait\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "C:\Users\ssjro\seait\ComfyUI\nodes.py", line 22, in <module>
    import comfy.diffusers_load
  File "C:\Users\ssjro\seait\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "C:\Users\ssjro\seait\ComfyUI\comfy\sd.py", line 7, in <module>
    from comfy import model_management
  File "C:\Users\ssjro\seait\ComfyUI\comfy\model_management.py", line 221, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ~~~~~~~~~~~~~~~~^^
  File "C:\Users\ssjro\seait\ComfyUI\comfy\model_management.py", line 172, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ssjro\seait\ComfyUI\venv\Lib\site-packages\torch\cuda\__init__.py", line 1026, in current_device
    _lazy_init()
    ~~~~~~~~~~^^
  File "C:\Users\ssjro\seait\ComfyUI\venv\Lib\site-packages\torch\cuda\__init__.py", line 363, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
launching ComfyUI at C:\Users\ssjro\seait\ComfyUI
Checkpoint files will always be loaded safely.
Traceback (most recent call last):
  File "C:\Users\ssjro\seait\ComfyUI\main.py", line 130, in <module>
    import execution
  File "C:\Users\ssjro\seait\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "C:\Users\ssjro\seait\ComfyUI\nodes.py", line 22, in <module>
    import comfy.diffusers_load
  File "C:\Users\ssjro\seait\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "C:\Users\ssjro\seait\ComfyUI\comfy\sd.py", line 7, in <module>
    from comfy import model_management
  File "C:\Users\ssjro\seait\ComfyUI\comfy\model_management.py", line 221, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ~~~~~~~~~~~~~~~~^^
  File "C:\Users\ssjro\seait\ComfyUI\comfy\model_management.py", line 172, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ssjro\seait\ComfyUI\venv\Lib\site-packages\torch\cuda\__init__.py", line 1026, in current_device
    _lazy_init()
    ~~~~~~~~~~^^
  File "C:\Users\ssjro\seait\ComfyUI\venv\Lib\site-packages\torch\cuda\__init__.py", line 363, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
launching ComfyUI at C:\Users\ssjro\seait\ComfyUI
Checkpoint files will always be loaded safely.
Traceback (most recent call last):
  File "C:\Users\ssjro\seait\ComfyUI\main.py", line 130, in <module>
    import execution
  File "C:\Users\ssjro\seait\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "C:\Users\ssjro\seait\ComfyUI\nodes.py", line 22, in <module>
    import comfy.diffusers_load
  File "C:\Users\ssjro\seait\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "C:\Users\ssjro\seait\ComfyUI\comfy\sd.py", line 7, in <module>
    from comfy import model_management
  File "C:\Users\ssjro\seait\ComfyUI\comfy\model_management.py", line 221, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ~~~~~~~~~~~~~~~~^^
  File "C:\Users\ssjro\seait\ComfyUI\comfy\model_management.py", line 172, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ssjro\seait\ComfyUI\venv\Lib\site-packages\torch\cuda\__init__.py", line 1026, in current_device
    _lazy_init()
    ~~~~~~~~~~^^
  File "C:\Users\ssjro\seait\ComfyUI\venv\Lib\site-packages\torch\cuda\__init__.py", line 363, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Updating ComfyUI at C:\Users\ssjro\seait\ComfyUI
Already up to date.

```
