### ISSUE TITLE
Install buttons disabled

### ISSUE THREAD

**Issue by igor-kurenkov** [diStyApps/seait#8]
All the install buttons disabled. But the Pythin install button. Python runs throught the installation process but then SEAIT still doesn't find the Python. Tried running in both user and administrator mode. Windows 10 x64
Actually i have a working automatic1111 installation, so i have python and git

**Comment by diStyApps** [comment]
Hey, it second report i get, do you know where your python installed? it regularly should be 
C:/Users/username/AppData/Loca/Programs/Python
But its is not the only checks it does, wonder why its not picking up.
ill look in to it.
But soon ill add options that you can set you own python git, or installations paths.

**Comment by mihau2** [comment]
Had the same problem as Igor. My Python was directly in C:\. 

After some trial and error, I copy-pasted it to C:/Users/username/AppData/Loca/Programs/Python/Python310, now it works.

**Comment by igor-kurenkov** [comment]
Tried the new version 0.0.7, still doesn't work

**Comment by igor-kurenkov** [comment]
> Try version 0.0.8; it should fix it.

Now it doesn't even show the GUI. Tried both 0.0.8 and 0.0.9

C:\seait_installers_version_0.0.8>seait
Traceback (most recent call last):
  File "seait.py", line 302, in <module>
  File "seait.py", line 37, in main
  File "layout\projects.py", line 60, in create_project_layout
  File "layout\requirements.py", line 15, in create_layout
  File "util\detect_python.py", line 38, in check_python
  File "util\detect_python.py", line 28, in get_python_installation
  File "subprocess.py", line 501, in run
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
PermissionError: [WinError 5] Access denied
[24716] Failed to execute script 'seait' due to unhandled exception!

**Comment by diStyApps** [comment]
Please try to download fresh installation of 0.0.9.

Unzip the contents of the "seait_installers_version_0.0.9" file to C:\TEST\seait_installers_version_0.0.9\seait.exe and launch it by clicking on it.

Although using C:\seait_installers_version_0.0.9 should have also functioned correctly.

**Comment by igor-kurenkov** [comment]
Sorry, same error, no GUI

**Comment by diStyApps** [comment]
Try to run seait.exe with RunAsAdministratorSymlink_seait.bat, which can be found here at [0.1.4](https://github.com/diStyApps/seait/releases/tag/0.1.4)

**Comment by igor-kurenkov** [comment]
Running as administrator.

Traceback (most recent call last):
  File "seait.py", line 334, in <module>
  File "seait.py", line 39, in main
  File "layout\projects.py", line 60, in create_project_layout
  File "layout\requirements.py", line 20, in create_layout
  File "util\dependency_check.py", line 6, in detect_python
  File "util\active_python_version.py", line 38, in check_python
  File "util\active_python_version.py", line 28, in get_python_installation
  File "subprocess.py", line 501, in run
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
PermissionError: [WinError 5] Отказано в доступе
[20300] Failed to execute script 'seait' due to unhandled exception!

**Comment by diStyApps** [comment]
Did you run at as administrator?

**Comment by igor-kurenkov** [comment]
Yes.
I don't know, if I am the only one who is having this problem, may be something is wrong with privileges on my pc

**Comment by Arch-Salt-Fish** [comment]
> Sorry, same error, no GUI

The same error occurs in version 0.0.14, if the installation folder is moved to a path that is different from where it was first run, and if you run seait.exe, the GUI does not appear.

**Comment by diStyApps** [comment]
Hey, there is dev version SEAIT 0.1.4.5 that inculdes setup installer should solve path and permissions issues.
Can be downloaded https://www.patreon.com/distyx
Tell me if that worked for you.

**Comment by diStyApps** [comment]
Try disable app execution aliases in windows: https://www.youtube.com/watch?v=EqhSXC1XfWM
